# Generated by Django 2.2 on 2022-01-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movidata',
            new_name='Moviedata',
        ),
    ]
