# Generated by Django 2.2 on 2022-01-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220107_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='type',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
